// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Xml.Linq;

using Azure.ApiManagement.PolicyToolkit.Authoring;
using Azure.ApiManagement.PolicyToolkit.Compiling.Diagnostics;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Azure.ApiManagement.PolicyToolkit.Compiling.Policy;

public class ValidateOdataRequestCompiler : IMethodPolicyHandler
{
    public string MethodName => nameof(IInboundContext.ValidateOdataRequest);

    public void Handle(ICompilationContext context, InvocationExpressionSyntax node)
    {
        if (!node.TryExtractingConfigParameter<ValidateOdataRequestConfig>(context, "validate-odata-request", out var values))
        {
            return;
        }

        var element = new XElement("validate-odata-request");

        if (!element.AddAttribute(values, nameof(ValidateOdataRequestConfig.MaxTop), "max-top"))
        {
            context.Report(Diagnostic.Create(
                CompilationErrors.RequiredParameterNotDefined,
                node.GetLocation(),
                "validate-odata-request",
                nameof(ValidateOdataRequestConfig.MaxTop)
            ));
            return;
        }

        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedQueryOptions), "allowed-query-options");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedFunctions), "allowed-functions");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedArithmeticOperators), "allowed-arithmetic-operators");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedLogicalOperators), "allowed-logical-operators");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedRelationalOperators), "allowed-relational-operators");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedAggregateFunctions), "allowed-aggregate-functions");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedGroupByProperties), "allowed-group-by-properties");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedOrderByProperties), "allowed-order-by-properties");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedExpandProperties), "allowed-expand-properties");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSelectProperties), "allowed-select-properties");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedFilterProperties), "allowed-filter-properties");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchProperties), "allowed-search-properties");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchOperators), "allowed-search-operators");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchFunctions), "allowed-search-functions");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchExpressions), "allowed-search-expressions");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchPhrases), "allowed-search-phrases");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchTerms), "allowed-search-terms");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchFields), "allowed-search-fields");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchFacets), "allowed-search-facets");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchHighlights), "allowed-search-highlights");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringProfiles), "allowed-search-scoring-profiles");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringFunctions), "allowed-search-scoring-functions");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringParameters), "allowed-search-scoring-parameters");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringWeights), "allowed-search-scoring-weights");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoosts), "allowed-search-scoring-boosts");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostFactors), "allowed-search-scoring-boost-factors");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostModes), "allowed-search-scoring-boost-modes");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostTypes), "allowed-search-scoring-boost-types");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostValues), "allowed-search-scoring-boost-values");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostRanges), "allowed-search-scoring-boost-ranges");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values, nameof(ValidateOdataRequestConfig.AllowedSearchScoringBoostIntervals), "allowed-search-scoring-boost-intervals");
        element.AddAttribute(values
